language: java
jdk:
- oraclejdk8
script: ant build
addons:
  sonarcloud:
    organization: "e6dc635aec6d791a01c3e018f2ec0edf8118e75d" # the key of the org you chose at step #3
    token:
      secure: ********* # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
