language: java
addons:
  sonarcloud:
    organization: "aegarro-github" # the key of the org you chose at step #3
    token:
      secure: e6dc635aec6d791a01c3e018f2ec0edf8118e75d # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
