language: java
addons:
  sonarcloud:
    organization: aegarro-github
    token:
      secure: e6dc635aec6d791a01c3e018f2ec0edf8118e75d 
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
